In [39]:
import torch

In [72]:
torch.manual_seed(42)

In [73]:
def print_tens_info(tensor):
    print("X :\n%s\n" % tensor)
    print("X количество измерений:\n%s\n" % tensor.dim())
    print("X размеры : ",  tensor.size())
    print("X тип : %s\n" % (tensor.type()))

In [74]:
# Создайте случайный FloatTensor размера 3x4x5
x=torch.rand((3,4,5))
print_tens_info(x)

X :
tensor([[[0.8823, 0.9150, 0.3829, 0.9593, 0.3904],
         [0.6009, 0.2566, 0.7936, 0.9408, 0.1332],
         [0.9346, 0.5936, 0.8694, 0.5677, 0.7411],
         [0.4294, 0.8854, 0.5739, 0.2666, 0.6274]],

        [[0.2696, 0.4414, 0.2969, 0.8317, 0.1053],
         [0.2695, 0.3588, 0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423]],

        [[0.6343, 0.3644, 0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895, 0.7539, 0.1952],
         [0.0050, 0.3068, 0.1165, 0.9103, 0.6440],
         [0.7071, 0.6581, 0.4913, 0.8913, 0.1447]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.FloatTensor



In [75]:
# Выведите его форму (shape)
x.shape

torch.Size([3, 4, 5])

In [76]:
# Альтернатива
x.size()

torch.Size([3, 4, 5])

In [81]:
# Приведите его к форме 6 X 10
x_6X10=x.reshape((6,10))
print_tens_info(x_6X10)

X :
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
         0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666,
         0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994, 0.5472,
         0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547,
         0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539,
         0.1952],
        [0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913,
         0.1447]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



In [82]:
# Alternative
x_6X10=x.view(6,10)
print_tens_info(x_6X10)

X :
tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566, 0.7936, 0.9408,
         0.1332],
        [0.9346, 0.5936, 0.8694, 0.5677, 0.7411, 0.4294, 0.8854, 0.5739, 0.2666,
         0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994, 0.5472,
         0.0062],
        [0.9516, 0.0753, 0.8860, 0.5832, 0.3376, 0.8090, 0.5779, 0.9040, 0.5547,
         0.3423],
        [0.6343, 0.3644, 0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539,
         0.1952],
        [0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071, 0.6581, 0.4913, 0.8913,
         0.1447]])

X количество измерений:
2

X размеры :  torch.Size([6, 10])
X тип : torch.FloatTensor



In [79]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
a=torch.FloatTensor([1, 4, 2, 2, 1])

print_tens_info(x*a)

X :
tensor([[[0.8823, 3.6600, 0.7657, 1.9186, 0.3904],
         [0.6009, 1.0263, 1.5873, 1.8815, 0.1332],
         [0.9346, 2.3743, 1.7388, 1.1354, 0.7411],
         [0.4294, 3.5418, 1.1478, 0.5332, 0.6274]],

        [[0.2696, 1.7655, 0.5938, 1.6634, 0.1053],
         [0.2695, 1.4353, 0.3987, 1.0944, 0.0062],
         [0.9516, 0.3011, 1.7720, 1.1664, 0.3376],
         [0.8090, 2.3117, 1.8080, 1.1093, 0.3423]],

        [[0.6343, 1.4576, 1.4209, 1.8928, 0.7890],
         [0.2814, 3.1545, 1.1789, 1.5078, 0.1952],
         [0.0050, 1.2273, 0.2330, 1.8205, 0.6440],
         [0.7071, 2.6325, 0.9826, 1.7826, 0.1447]]])

X количество измерений:
3

X размеры :  torch.Size([3, 4, 5])
X тип : torch.FloatTensor



In [83]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
print_tens_info(torch.mm(x_6X10,x_6X10.T))

X :
tensor([[4.7945, 3.8096, 2.5222, 3.8582, 3.9556, 3.2959],
        [3.8096, 4.6157, 2.0199, 4.0262, 4.0298, 2.7789],
        [2.5222, 2.0199, 1.5990, 1.9847, 2.3031, 2.0095],
        [3.8582, 4.0262, 1.9847, 4.3807, 3.7802, 2.8199],
        [3.9556, 4.0298, 2.3031, 3.7802, 4.2133, 3.2752],
        [3.2959, 2.7789, 2.0095, 2.8199, 3.2752, 3.3410]])

X количество измерений:
2

X размеры :  torch.Size([6, 6])
X тип : torch.FloatTensor



In [84]:
#Alternative
print_tens_info(torch.mm(x_6X10,torch.transpose(x_6X10,1,0)))

X :
tensor([[4.7945, 3.8096, 2.5222, 3.8582, 3.9556, 3.2959],
        [3.8096, 4.6157, 2.0199, 4.0262, 4.0298, 2.7789],
        [2.5222, 2.0199, 1.5990, 1.9847, 2.3031, 2.0095],
        [3.8582, 4.0262, 1.9847, 4.3807, 3.7802, 2.8199],
        [3.9556, 4.0298, 2.3031, 3.7802, 4.2133, 3.2752],
        [3.2959, 2.7789, 2.0095, 2.8199, 3.2752, 3.3410]])

X количество измерений:
2

X размеры :  torch.Size([6, 6])
X тип : torch.FloatTensor



In [85]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
from torch.autograd import Variable
x = Variable(torch.FloatTensor([1]),   requires_grad = True)
z = Variable(torch.FloatTensor([0.5]), requires_grad = True)
t = Variable(torch.FloatTensor([2]),   requires_grad = True)

y = x**3 + z -75*t

y.backward([x, z, t])

(x.grad, z.grad, t.grad)

(tensor([3.]), tensor([1.]), tensor([-75.]))

In [89]:
# Создайте единичный тензор размера 5x6
ones_5X6=torch.ones(5,6)
print_tens_info(ones_5X6)

X :
tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

X количество измерений:
2

X размеры :  torch.Size([5, 6])
X тип : torch.FloatTensor



In [95]:
# Переведите его в формат numpy
np_arr=ones_5X6.numpy()
print(f'np_arr :\n{np_arr}\n'
      f'\nnp_arr размеры : \n{np_arr.shape}\n'
      f'\nnp_arr тип : \n{type(np_arr)}\n')

np_arr :
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]

np_arr размеры : 
(5, 6)

np_arr тип : 
<class 'numpy.ndarray'>



In [96]:
# возьмите функцию y = x**w1 - 2 * x**2 + 5
# Посчитайте 
from torch import nn 
from torch import optim

In [97]:
x = torch.FloatTensor([1])
w1 = Variable(torch.FloatTensor([1]), requires_grad=True)

y = x**w1 - 2*x**2 + 5

In [111]:
criterion = nn.MSELoss()
optimizer = optim.SGD([w1], lr=0.001)

In [112]:
layer=nn.Linear(1,1,bias=False)

In [116]:
optimizer.zero_grad()
x = torch.FloatTensor([3])

pred = x ** layer(torch.FloatTensor([1])) -2 * x**2 + 5
loss = criterion(pred, y)
loss

tensor(274.7013, grad_fn=<MseLossBackward>)

In [117]:
loss.backward()
optimizer.step()

In [118]:
pred

tensor([-12.5741], grad_fn=<AddBackward0>)

In [120]:
print(layer)
print(layer.weight.grad)

Linear(in_features=1, out_features=1, bias=False)
tensor([[-15.5095]])


extra *

https://www.tensorflow.org/tutorials/quickstart/beginner

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=decc2051-1015-41c7-b089-ef8e037f6b10' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>